-- ==================================================================
-- CONFIG TABLE
-- ==================================================================
CREATE OR REPLACE TABLE DATABASE_NAME.SCHEMA_NAME.DQ_TABLE_CONFIG (
    STG_TABLE STRING,
    INT_TABLE STRING,
    HIST_TABLE STRING,
    KEYS STRING -- JSON array of key columns
);

-- Example insert
INSERT INTO DATABASE_NAME.SCHEMA_NAME.DQ_TABLE_CONFIG
VALUES (
  'DATABASE_NAME.SCHEMA_NAME.STG_BILLING_LINE_DETAILS',
  'DATABASE_NAME.SCHEMA_NAME.INT_BILLING_LINE_DETAILS',
  'DATABASE_NAME.SCHEMA_NAME.HIST_BILLING_LINE_DETAILS',
  '["BILLINGLINEDETAILID"]'

);
